language: r
r: bioc-devel
sudo: false
cache: packages
warnings_are_errors: false
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
addons:
  apt:
    packages:
      - libfftw3-dev
      - libnetcdf-dev
      - netcdf-bin
