language: r
r:
  - devel
sudo: false
cache: packages
bioc_required: true
warnings_are_errors: false
# Used for code coverage testing with covr and codecov
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
